### ISSUE TITLE
readme example

### ISSUE THREAD

**Issue by marregui** [questdb/py-questdb-query#1]
1. I have cloned the repo

2. I have created table "cpu" like so (this is missing in the README):

    ```sql
    CREATE TABLE cpu  AS (
        SELECT
            rnd_symbol(4,4,4,2) hostname,
            rnd_symbol(4,4,4,2) datacenter,
            rnd_int() usage_user,
            rnd_int() usage_nice,
            timestamp_sequence(
                to_timestamp(
                    '2023-04-14T17:00:00', 
                    'yyyy-MM-ddTHH:mm:ss'), 
                100000L) timestamp
        FROM long_sequence(10000)
    ) TIMESTAMP(timestamp) PARTITION BY DAY WAL;
    ```

3. I have installed the project like so:
  
    ```bash
    poetry install
    poetry shell
    python --version
    (Python 3.10.12)
    python
    ```

4. I have started an interactive python interpreter and have executed the example:

    ```python
    from questdb_query import numpy_query
    np_arrs = numpy_query(
            '''
            select
                timestamp, hostname, datacenter, usage_user, usage_nice
            from
                cpu
            limit 10
            '''
    )
    ```

The result:

```bash
>>> np_arrs = numpy_query(
...     '''
...     select
...         timestamp, hostname, datacenter, usage_user, usage_nice
...     from
...         cpu
...     limit 10
...     '''
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marregui/workspace/py-questdb-query/questdb_query/synchronous.py", line 29, in numpy_query
    df = pandas_query(query, endpoint, chunks)
  File "/Users/marregui/workspace/py-questdb-query/questdb_query/synchronous.py", line 23, in pandas_query
    return asyncio.run(a.pandas_query(query, endpoint, chunks))
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/marregui/workspace/py-questdb-query/questdb_query/asynchronous.py", line 108, in pandas_query
    result_schema, row_count = await _pre_query(session, endpoint, query)
  File "/Users/marregui/workspace/py-questdb-query/questdb_query/asynchronous.py", line 47, in _pre_query
    columns = [
  File "/Users/marregui/workspace/py-questdb-query/questdb_query/asynchronous.py", line 48, in <listcomp>
    (col['name'], dtypes_map[col['type'].upper()])
KeyError: 'INT'
```

**Comment by marregui** [comment]
completed
