### ISSUE TITLE
Exception in pandas_query() if a query returns 0 rows

### ISSUE THREAD

**Issue by kasparthommen** [questdb/py-questdb-query#7]
Try this:

```python
from questdb_query import Endpoint, pandas_query

endpoint = Endpoint(host='demo.questdb.io', https=True)
df = pandas_query('select * from trades limit 0', endpoint)
```

This should return a pandas data frame with 0 rows, but instead it produces the following exception:

```
Series([], Name: timestamp, dtype: float64)
Traceback (most recent call last):
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\questdb_query\asynchronous.py", line 124, in _read_csv
    series = pd.to_datetime(series).dt.tz_convert(None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\pandas\core\accessor.py", line 112, in f
    return self._delegate_method(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\pandas\core\indexes\accessors.py", line 132, in _delegate_method
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\pandas\core\indexes\datetimes.py", line 283, in tz_convert
    arr = self._data.tz_convert(tz)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\pandas\core\arrays\datetimes.py", line 915, in tz_convert
    raise TypeError(
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3c94757294d3>", line 4, in <module>
    df = pandas_query('select * from trades limit 0', endpoint)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\questdb_query\synchronous.py", line 33, in pandas_query
    return asyncio.run(a.pandas_query(query, endpoint, chunks, timeout))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\questdb_query\asynchronous.py", line 164, in pandas_query
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\questdb_query\asynchronous.py", line 133, in _query_pandas
    df = await loop.run_in_executor(executor, _read_csv)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xxx\.conda\envs\p312\Lib\site-packages\questdb_query\asynchronous.py", line 128, in _read_csv
    raise ValueError(
ValueError: Failed to convert column timestamp to type TIMESTAMP: Cannot convert tz-naive timestamps, use tz_localize to localize
Series([], Name: timestamp, dtype: float64)
```

**Comment by amunra** [comment]
Fix is on its way.

**Comment by amunra** [comment]
Fix merged.

**Comment by kasparthommen** [comment]
That was quick - thanks, I can confirm that it works now!
